config/routes.rb
UmAkl::Application.routes.draw do
  devise_for :users

  resources :users
  resources :donations
  resources :posts

  root :to => "Posts#index"

end

app/models/creator.rb
class Creator
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :email, type: String

  embedded_in :createable, polymorphic: true
  belongs_to :user
end

app/models/message.rb
class Message
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title, type: String
  field :body, type: String

  belongs_to :user
  belongs_to :messageable, polymorphic: true
end

app/models/post.rb
class Post
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title, type: String
  field :message, type: String

  validates_presence_of :title, :message

  has_many :children, :class_name => "Post", :foreign_key => :parent_id
  accepts_nested_attributes_for :children

  belongs_to :parent, :class_name => "Post"
  belongs_to :top_parent, :class_name => "Post"

  embeds_one :creator, as: :createable

  before_save :set_top_parent

  def set_top_parent
    self.top_parent = find_top_parent
  end

  def find_top_parent
    if self.parent_id.nil?
      self
    elsif self.parent.top_parent
      self.parent.top_parent
    else
      self.parent.find_top_parent
    end
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :token_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable, :encryptable, :confirmable, :lockable

  field :name, type: String, :null => false
  validates_presence_of :name

  ## Database authenticatable
  field :email,              :type => String, :null => false, :default => ""
  field :encrypted_password, :type => String, :null => false, :default => ""

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Encryptable
  field :password_salt, :type => String

  ## Confirmable
  field :confirmation_token,   :type => String
  field :confirmed_at,         :type => Time
  field :confirmation_sent_at, :type => Time
  field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  field :locked_at,       :type => Time

  ## Token authenticatable
  field :authentication_token, :type => String

  def as_creator
    Creator.new(name: self.name, email: self.email, user: self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate_user!
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.where(parent_id: nil).order_by(:_id.desc)
  end

  def new
    @post = Post.new(params[:post])
    @post.message ||= Message.new
  end

  def create
    @post = Post.new(params[:post])
    @post.creator = current_user.as_creator

    if @post.save
      redirect_to @post.top_parent
    else
      render :action => "new", :status => 422
    end
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.haml
!!! XML
!!!
%html
  %head
    %title University of Montevallo - AKL
    = stylesheet_link_tag    "application", "formtastic", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %header
    %nav
      = render partial: "shared/menu"

    - if user_signed_in?
      = link_to "Logout", destroy_user_session_path, :method => :delete

    = yield

    %footer

app/views/posts/_form.html.haml
- post, form = form, nil
= semantic_form_for post do |form|
  = form.inputs do
    = form.input :title
    = form.input :message, :as => :text
  = form.buttons

app/views/posts/_post.html.haml
%li{class: first ? "first" : nil}
  = link_to(post.title, post)
  = link_to(post.creator.name, user_path(post.creator.user_id), class: "secondary")
  = post.updated_at > 3.days.ago ? time_ago_in_words(post.updated_at) : post.updated_at.to_s(:date)

  - if post.children.present?
    %ul#children
      = render partial: "post", collection: post.children

app/views/posts/index.html.haml
= link_to "New Thread", new_post_path

%ul#posts
  = render partial: "post", collection: @posts.limit(50), locals: {first: true}

app/views/posts/new.html.haml
%h1 New Post

= semantic_form_for @post do |form|
  = form.fields_for :message do |message_form|
    = form.inputs do
      = form.input :title
      = message_form.input :body, :as => :text
  = form.buttons

app/views/posts/show.html.haml
= link_to "Back", posts_path

%h1= @post.title

Posted by #{link_to @post.creator.name, user_path(@post.creator.user_id)} #{@post.created_at < 3.days.ago ? @post.created_at.to_s(:date) : time_ago_in_words(@post.created_at)} ago

:markdown
  #{@post.message}

= render :partial => "form", object: Post.new(:parent => @post)

app/views/shared/_menu.html.haml
#menu
  .link
    = link_to "Virtual Chapter Room", posts_path
  .link
    = link_to "Brothers", users_path
  .link
    = link_to "Chapter Bank", donations_path